apiVersion: apps/v1
kind: Deployment
metadata:
  name: cardano-core-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cardano-core-node
  template:
    metadata:
      labels:
        app: cardano-core-node
    spec:
      volumes:
        - name: cardano-db
          persistentVolumeClaim:
            claimName: cardano-db-pvc
        - name: cardano-config
          configMap:
            name: cardano-core-config

      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
      initContainers:
        - name: fix-permissions
          image: busybox
          securityContext:
            runAsUser: 0
          command:
            [
              "sh",
              "-c",
              "chown -R 1000:1000 /cardano/data && chmod -R 775 /cardano/data",
            ]
          volumeMounts:
            - name: cardano-db
              mountPath: /cardano/data
        - name: mithril-bootstrap
          image: ghcr.io/input-output-hk/mithril-client:main-9a2faa1
          env:
            - name: AGGREGATOR_ENDPOINT
              value: https://aggregator.release-preprod.api.mithril.network/aggregator
          volumeMounts:
            - name: cardano-db
              mountPath: /cardano/data
          command: ["/bin/bash", "-c"]
          args: [
              "/app/bin/mithril-client cardano-db
              download
              --download-dir /cardano/data
              latest",
            ]

      containers:
        - name: cardano-core-node
          image: ghcr.io/intersectmbo/cardano-node:10.2.1
          ports:
            - containerPort: 3001
          volumeMounts:
            - name: cardano-config
              mountPath: /config
            - name: cardano-db
              mountPath: /cardano/data
          command: ["/bin/bash", "-c"]
          args: [
              "cardano-node run
              --topology /config/topology.json
              --database-path /cardano/data/db
              --socket-path /cardano/data/db/node.socket
              --port 3001 --config /config/config.json",
            ]
          # resources:
          #   requests:
          #     memory: "4Gi"
          #     cpu: "2"
