apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cardano

configMapGenerator:
  - name: cardano-core-config
    files:
      - ./configs/common/topology.json
      - ./configs/common/config.json
      - ./configs/common/alonzo-genesis.json
      - ./configs/common/byron-genesis.json
      - ./configs/common/conway-genesis.json
      - ./configs/common/shelley-genesis.json

  - name: db-sync-config
    files:
      - ./configs/common/db-sync-config.json
      - ./configs/common/config.json
      - ./configs/common/alonzo-genesis.json
      - ./configs/common/byron-genesis.json
      - ./configs/common/conway-genesis.json
      - ./configs/common/shelley-genesis.json

generatorOptions:
  disableNameSuffixHash: true

resources:
  - ./core-node-pvc.yaml
  - ./core-node-dp.yaml
  - ./core-node-svc.yaml

  - ./postgresql-sts.yaml
  - ./postgresql-svc.yaml
  - ./db-sync-dp.yaml
