apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cardano

configMapGenerator:
  - name: core-node-config
    files:
      - ./configs/core-node-topology.json
      - ./configs/core-node-config.json
      - ./configs/alonzo-genesis.json
      - ./configs/byron-genesis.json
      - ./configs/conway-genesis.json
      - ./configs/shelley-genesis.json
      - ./configs/db-sync-config.json

  - name: relay-node-config
    files:
      - ./configs/relay-node-topology.json
      - ./configs/relay-node-config.json
      - ./configs/alonzo-genesis.json
      - ./configs/byron-genesis.json
      - ./configs/conway-genesis.json
      - ./configs/shelley-genesis.json
      - ./configs/db-sync-config.json

generatorOptions:
  disableNameSuffixHash: true

resources:
  - ./postgresql-sts.yaml
  - ./postgresql-svc.yaml
  - ./core-node-sts.yaml
  - ./core-node-svc.yaml
  - ./relay-node-sts.yaml
  - ./relay-node-svc.yaml
  - ./relay-node-hpa.yaml
