apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: relay-node
spec:
  volumeClaimTemplates:
    - metadata:
        name: cardano-data
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "20Gi"
  # serviceName: relay-node
  replicas: 2
  selector:
    matchLabels:
      app: relay-node
  template:
    metadata:
      labels:
        app: relay-node
    spec:
      volumes:
        - name: cardano-config
          configMap:
            name: relay-node-config

      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
      initContainers:
        - name: fix-permissions
          image: busybox
          securityContext:
            runAsUser: 0
          command:
            [
              "sh",
              "-c",
              "chown -R 1000:1000 /cardano/data && chmod -R 775 /cardano/data",
            ]
          volumeMounts:
            - name: cardano-data
              mountPath: /cardano/data
        - name: mithril-bootstrap
          image: ghcr.io/input-output-hk/mithril-client:main-9a2faa1
          env:
            - name: AGGREGATOR_ENDPOINT
              value: https://aggregator.release-preprod.api.mithril.network/aggregator
          volumeMounts:
            - name: cardano-data
              mountPath: /cardano/data
          command: ["/bin/bash", "-c"]
          args:
            - |
              if [ -z "$(ls -A /cardano/data/db)" ]; then
                echo "Start bootstrap"
                /app/bin/mithril-client cardano-db download --download-dir /cardano/data latest
              else
                echo "Skip bootstrap"
              fi
      containers:
        - name: relay-node
          image: ghcr.io/intersectmbo/cardano-node:10.2.1
          ports:
            - containerPort: 3001
          volumeMounts:
            - name: cardano-config
              mountPath: /config
            - name: cardano-data
              mountPath: /cardano/data
          command: ["/bin/bash", "-c"]
          # args: ["sleep 1d"]
          args: [
              "cardano-node run
              --topology /config/relay-node-topology.json
              --database-path /cardano/data/db
              --socket-path /cardano/data/db/node.socket
              --port 3001 --config /config/relay-node-config.json",
            ]
          resources:
            requests:
              cpu: "200m"
              memory: "1Gi"
            limits:
              cpu: "2"
              memory: "4Gi"
